nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN-unexists}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.0.2.cjs

changesetBaseRefs:
  - 'main'
  - 'origin/main'
  - 'upstream/main'
